### ISSUE TITLE
No config-file created

### ISSUE THREAD

**Issue by 1TheCrazy** [DJtheRedstoner/DevAuth#14]
I recently started using DevAuth for the first time and it just wouldn't create a config.toml file, nor the directory. But it wasn't throwing any errors. The only consequence was, that I couldn't use DevAuth and it always logged: 'DevAuth deisabled, not logging in!'. I tried to set the JVM properties, but cmd threw an error that therre was no base class 'devauth.enabled', the IntelliJ menu Help > Edit Custom VM Properties didn't work (I didn't try the Help >  Edit Custom Properties, but I figure it wouldn't have worked aswell) and also the Run > Debug... > Edit Configurations > Environment Variables didn't help. I've never used java or the JVM before, but that was what google suggested to change the JVM properties mentioned in the [README.md](https://github.com/DJtheRedstoner/DevAuth?tab=readme-ov-file#configuration) file.
What I had to do to get it working in the end, was to create the directory myself and configure the config.toml file like this:
```toml
defaultEnabled = true

defaultAccount = "main"

# An example mojang account
[accounts.main]
type = "microsoft"

[accounts.alt]
type = "microsoft"
```
I tried backtracking throught the code in the repository to find why it didn't throw any errors or created a default config(DevAuthJava l.33) but couldn't find the reason.
For my project I'm using Java 8 as a Project SDK (if that helps to find the source of the issue) and I'm on Windows 11
